import './globals.css'
import { Nunito } from 'next/font/google'
import Navbar from "@/components/navbar/Navbar";
import MountedClient from "@/components/MountedClient";
import RegisterModal from "@/components/modals/RegisterModal";
import AtomProvider from "@/providers/AtomProvider";
import LoginModal from "@/components/modals/LoginModal";
import ToastProvider from "@/providers/ToastProvider";
import getCurrentUser from "@/actions/getCurrentUser";
import ElementModal from "@/components/modals/ElementModal";

const font = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({children,}: { children: React.ReactNode }) {
    const user = await getCurrentUser()
  return (
    <html lang="en">
      <body className={font.className}>
      <AtomProvider>
          <MountedClient>
              <ToastProvider/>
              <RegisterModal/>
              <LoginModal/>
              <ElementModal/>
              <Navbar user={user}/>
          </MountedClient>
          <main className="h-full bg-gradient-to-r from-[#BED1Fc] to-[#FFF7FA]">{children}</main>
      </AtomProvider>
      </body>
    </html>
  )
}
