import './globals.css'
import { Nunito } from 'next/font/google'
import Navbar from "@/components/navbar/Navbar";
import MountedClient from "@/components/MountedClient";
import Index from "@/components/modals/Modal";
import RegisterModal from "@/components/modals/RegisterModal";

const font = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={font.className}>
      <MountedClient>
          <RegisterModal/>
          <Navbar/>
      </MountedClient>
      <main>{children}</main>
      </body>
    </html>
  )
}
